### ISSUE TITLE
Haskell always recompiles

### ISSUE THREAD

**Issue by cburgmer** [cburgmer/json-path-comparison#19]
It seems Cabal uses a symlink which ninja detects as a change and hence forces a rebuild everytime. This is a performance issue which will slow down repeated builds.

It seems there is an option to not use a symlink (https://cabal.readthedocs.io/en/latest/nix-local-build.html#cabal-v2-install), but it's not available in the current version:

    cabal v2-install exe:cabal --install-method=copy --installdir=~/bin

Tried upgrading to 3.0.0.0 but that fails.

@akshaymankar any ideas?

**Comment by akshaymankar** [comment]
Yeah, the upgrade to 3.x will fail because they haven't released pre-built binaries for alpine. I am hoping they release one in the next 3.x version.
In the meantime we can do one of these things:
1. Build docker on ubuntu base image and then use cabal 3.x. It can even be installed using apt thanks to [this ppa](https://launchpad.net/~hvr/+archive/ubuntu/ghc)
1. Use cabal 2.4 and copy the binary using `cp` after it is built.
1. Run docker with `-v /tmp/cabal-cache:/root/.cabal` to make sure cabal doesn't rebuild everything again.
1. Build cabal 3.0.0.0 binary in Dockerfile. This will make `docker build` slow.

**Comment by cburgmer** [comment]
I'm personally OK with a quick hack, especially if the proper solution is still in the making.

**Comment by akshaymankar** [comment]
Option 3 would be the easiest then :)

**Comment by cburgmer** [comment]
I'm having problems running ninja locally without Docker (currently I'd like to support both), as I cannot install an older cabal easily via homebrew. It seems unfortunate to be stuck between two versions. I'll play around with some options.

**Comment by akshaymankar** [comment]
Does it not work with newer version of cabal?

**Comment by cburgmer** [comment]
It seems 3.0.0.0 breaks the API.

**Comment by cburgmer** [comment]
It works now both with Cabal 2.4.1.0 and Cabal 3.0.0.0. Once Alpine is able to follow up on the version change we can remove the special handling.
