### ISSUE TITLE
Clamping of array indices in Proposal A

### ISSUE THREAD

**Issue by glyn** [cburgmer/json-path-comparison#57]
The handling of excessively large and excessively small array indices seems to be inconsistent:
```
$ echo '[0,1,2,3,4]' | ./run.sh '$[-99]'
[0]
$ echo '[0,1,2,3,4]' | ./run.sh '$[99]'
[]
```
For consistency, either the first of these should return `[]` (which would be consistent with Göessner) or the second should return `[4]`.

Note that Python behaviour does not help guide us as it will give an array out of bounds error.

Perhaps there is a good reason for this behaviour, in which case it would be good to document it.

**Comment by remorhaz** [comment]
> Python behaviour does not help guide us as it will give an array out of bounds error

I interpreted Python errors as guide for returning an empty result.

**Comment by cburgmer** [comment]
We were indeed missing a query for this case, I added one: https://cburgmer.github.io/json-path-comparison/results/bracket_notation_with_negative_number_on_short_array.html

Turns out that Proposal A is not aligned with the consensus, and I would say the proposal is also plain wrong

IMHO this should also correlate with the positive number case which shows a clear consensus: https://cburgmer.github.io/json-path-comparison/results/bracket_notation_with_number_on_short_array.html

Should we change Proposal A's implementation in this case?

**Comment by glyn** [comment]
> Should we change Proposal A's implementation in this case?

Yes, I think so.

**Comment by cburgmer** [comment]
Pushed a change, happy to see this closed if you agree.

**Comment by glyn** [comment]
Yes, the fix seems good. Thanks.
