### ISSUE TITLE
Divergent behaviour with large array indices in Proposal A

### ISSUE THREAD

**Issue by glyn** [cburgmer/json-path-comparison#59]
The following demonstrates an example:
```
$ echo '[0,1,2,3,4]' | ./run.sh '$[2:113667776004]'
...
FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory
...
```
This failure is analogous:
```
$ echo '[0,1,2,3,4]' | ./run.sh '$[113667776004:0:-1]'
...
FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory
...
```

This class of divergent behaviour was found by fuzz testing in https://github.com/vmware-labs/yaml-jsonpath/pull/30.

**Comment by cburgmer** [comment]
Love the fuzzer, thanks for flagging.

I think we can agree that Proposal A's implementation in this part does not cover this input. At the time of writing it was more important for me to find a concise way of expressing the general intent, not so much trying to capture all cross functional requirements (like speed or low memory consumption).

The reason for this is that I don't believe that JSONPath can be implemented in exactly one way, but on the contrary, different implementations might focus on different aspects with different tradeoffs.

The case you flagged is somewhat borderline, so maybe we change this.

Related: What's going to be the arbiter on the one and only JSONPath truth in the end. The written standard, or the conjoined implementation?

**Comment by cburgmer** [comment]
Actually, now that I fixed the issue in the Proposal (had to add 4 test cases), I can see value in calling out this detail in a standard. Or at least to make sure this is captured in the reference test suite.

On that note, I'm not sure whether we agree on which document will become the test suite we want to push. Currently the Proposal A's own test suite is lagging a bit behind the one from the consensus. My personal goal was to drive forward the one from the consensus, which is why I'm adding more queries to the consensus for every issue you raise.
What do you think?

In that sense, I'd like to keep this issue open until I added the 4 necessary queries to the consensus itself.

**Comment by glyn** [comment]
I agree we should focus on the consensus test suite.

> Related: What's going to be the arbiter on the one and only JSONPath truth in the end. The written standard, or the conjoined implementation?

I think it has to be the written standard in the end as we can't afford to maintain code indefinitely. This is the view taken by the IETF in [RFC 7942](https://tools.ietf.org/html/rfc7942) which advises stripping out the implementations section before promoting an Internet Draft to a RFC.

**Comment by cburgmer** [comment]
I've changed Proposal A's handling. (Although I haven't spent time on refactoring, which might be necessary now that the logic is more complex.)
I've also added 4 test cases for begin and end for positive and negative steps each.
From my side I feel all is done.
